require "octo".setup({
    enable_builtin = true,
    mappings_disable_default = true,
    mappings = {
        pull_request = {
            list_commits = { lhs = "<localleader>lc", desc = "list PR commits" },
            list_changed_files = { lhs = "<localleader>lf", desc = "list PR changed files" },
            reload = { lhs = "<localleader>rp", desc = "reload PR" },
            open_in_browser = { lhs = "<localleader>op", desc = "open PR in browser" },
            copy_url = { lhs = "<localleader>cp", desc = "copy url to system clipboard" },
            add_comment = { lhs = "<localleader>ac", desc = "add comment" },
            delete_comment = { lhs = "<localleader>dc", desc = "delete comment" },
            next_comment = { lhs = "<localleader>nc", desc = "go to next comment" },
            prev_comment = { lhs = "<localleader>pc", desc = "go to previous comment" },
            review_start = { lhs = "<localleader>sr", desc = "start a review for the current PR" },
            review_resume = { lhs = "<localleader>rr", desc = "resume a pending review for the current PR" },
        },
        review_thread = {
            add_comment = { lhs = "<localleader>ac", desc = "add comment" },
            add_suggestion = { lhs = "<localleader>as", desc = "add suggestion" },
            delete_comment = { lhs = "<localleader>dc", desc = "delete comment" },
        },
        submit_win = {
            approve_review = { lhs = "<localleader>a", desc = "approve review" },
            comment_review = { lhs = "<localleader>c", desc = "comment review" },
            request_changes = { lhs = "<localleader>r", desc = "request changes review" },
            close_review_tab = { lhs = "<localleader>x", desc = "close review tab" },
        },
        review_diff = {
            add_review_comment = { lhs = "<localleader>ac", desc = "add a new review comment" },
            add_review_suggestion = { lhs = "<localleader>as", desc = "add a new review suggestion" },
            next_thread = { lhs = "<localleader>nt", desc = "move to next thread" },
            prev_thread = { lhs = "<localleader>pt", desc = "move to previous thread" },
            select_next_entry = { lhs = "<localleader>nf", desc = "move to next changed file" },
            select_prev_entry = { lhs = "<localleader>pf", desc = "move to previous changed file" },
            toggle_viewed = { lhs = "<localleader>fv", desc = "toggle viewer viewed state" },
        },
        file_panel = {
            submit_review = { lhs = "<localleader>sr", desc = "submit review" },
            discard_review = { lhs = "<localleader>dr", desc = "discard review" },
            next_entry = { lhs = "j", desc = "move to next changed file" },
            prev_entry = { lhs = "k", desc = "move to previous changed file" },
            select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
            refresh_files = { lhs = "<localleader>rf", desc = "refresh changed files panel" },
            select_next_entry = { lhs = "<localleader>fd", desc = "move to next changed file" },
            select_prev_entry = { lhs = "<localleader>fu", desc = "move to previous changed file" },
            toggle_viewed = { lhs = "<localleader>fv", desc = "toggle viewer viewed state" },
        },
    },
})
