#!/usr/bin/env bash

selected=$(dotnet sln list | tail -n+3 | fzf --scheme path --query="$1" --select-1 --exit-0)

if [[ -z $selected ]]; then
    exit 0
fi

dotnet run --project $selected "$@"
exit 0
