#!/bin/zsh

printf "\033]2;theme-switcher\a"

appearance=$(echo "light,dark" | tr , "\n" | fzf --height=4 --no-input)

theme=$(cat "${HOME}/.bin/themes-${appearance}.txt" | fzf)

# Update ghostty theme
sd "^(theme.*${appearance}:)[A-Za-z-\s]+(,?.*)$" "\${1}${theme}\${2}" $HOME/.config/ghostty/config

# Update nvim theme
sd "^(.*${appearance} = \").+(\".*)$" "\${1}${theme}\${2}" $HOME/.config/nvim/lua/helpers/theming.lua
