#!/usr/bin/env bash

if [[ -z $TMUX ]]; then
    echo 'Not in a tmux session'
    exit 1
fi

tmux send-keys 'nvim .' C-m

tmux rename-window Neovim

tmux new-window -d -n Cursor agent

tmux new-window -d -n Other
