#!/usr/bin/env bash

printf "\033]2;tmux-attacher\a"

selected=$(tmux ls | fzf --exit-0 --bind "ctrl-x:execute-silent(tmux kill-session -t {1})+reload(tmux ls)")

if [[ -z $selected ]]; then
    exit 0
fi

session_name="$(cut -d ':' -f1 <<< "$selected")"

if [[ -z $TMUX ]]; then
    tmux attach -t $session_name
    exit 0
fi

tmux switch-client -t $session_name
