#!/usr/bin/env bash

selected=$(find ~/Code -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]]; then
    tmux new-session -A -s $selected_name -c $selected
    exit 0
fi

tmux new-session -ds $selected_name -c $selected

tmux switch-client -t $selected_name
