#!/bin/zsh

source ~/.config/zsh/sources/tmux.zsh

printf "\033]2;tmux-attacher\a"

selected=$(tmux ls | fzf --exit-0 --bind "ctrl-x:execute-silent(tmux kill-session -t {1})+reload(tmux ls)")

if [[ -z $selected ]]; then
    exit 0
fi

session_name="$(cut -d ':' -f1 <<< "$selected")"

tmux-attach $session_name
