[general]
import = ["themes/catppuccin-macchiato.toml"]

[window]
padding = { x = 8, y = 8 }
resize_increments = true
option_as_alt = "OnlyRight"
decorations = "Buttonless"
opacity = 0.95
blur = false

[font]
normal = { family = "RobotoMono Nerd Font", style= "Regular" }
size = 14
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block" }

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = "Back", mods = "Command", chars = "\u0015" }]
